CREATE TABLE USER (
    ID VARCHAR(40) NOT NULL,
    NAME VARCHAR(100) NOT NULL,
    TITLE VARCHAR(40) NOT NULL,
    primary key PRIMARY_KEY(ID)
);

INSERT INTO USER(ID, NAME, TITLE) VALUES ('id-1','Davis','DEV');
INSERT INTO USER(ID, NAME, TITLE) VALUES ('id-2','Ben','DEV');
INSERT INTO USER(ID, NAME, TITLE) VALUES ('id-3','ABC','QA');
INSERT INTO USER(ID, NAME, TITLE) VALUES ('id-4','DDD','QA');
INSERT INTO USER(ID, NAME, TITLE) VALUES ('id-5','Test','QA');
INSERT INTO USER(ID, NAME, TITLE) VALUES ('id-6','Joy','QA');