CREATE TABLE PRODUCT (
    ID VARCHAR(40) NOT NULL,
    NAME VARCHAR(100) NOT NULL,
    TITLE VARCHAR(40) NOT NULL,
    PRIMARY KEY PRIMARY_KEY(ID)
);

INSERT INTO PRODUCT(ID, NAME, TITLE) VALUES ('p-1','Apple','Fruit');
INSERT INTO PRODUCT(ID, NAME, TITLE) VALUES ('p-2','Banana','Fruit');
INSERT INTO PRODUCT(ID, NAME, TITLE) VALUES ('p-3','DDD','Book');
INSERT INTO PRODUCT(ID, NAME, TITLE) VALUES ('p-4','SOA','Book');
INSERT INTO PRODUCT(ID, NAME, TITLE) VALUES ('p-5','iPhone 14','Phone');
INSERT INTO PRODUCT(ID, NAME, TITLE) VALUES ('p-6','Vivo X100','Phone');
